CREATE TABLE posts_p1 PARTITION OF posts
FOR VALUES WITH (MODULUS 3, REMAINDER 0);

CREATE TABLE posts_p2 PARTITION OF posts
FOR VALUES WITH (MODULUS 3, REMAINDER 1);

CREATE TABLE posts_p3 PARTITION OF posts
FOR VALUES WITH (MODULUS 3, REMAINDER 2);
